Database check

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -56,9 +56,17 @@ jobs:
 
     - name: 1 Test
       run: |
-        if curl -f http://localhost:${{ secrets.APP_PORT }}/health; then
+        if curl -f http://localhost:${{ secrets.APP_PORT }}; then
           echo "Web application is healthy"
         else
           echo "Web application health check failed"
         exit 1
+        fi
+
+        DATABASE_RESPONSE=$(curl -s http://localhost:${{ secrets.APP_PORT }}/check_db)
+        if [ $? -eq 0 ]&& echo "$DATABASE_RESPONSE" | grep -q "База успешно подключена"; then
+          echo "Application database connection working"
+        else
+          echo "Application database connection failed"
+          exit 1
         fi
